imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: vespolina.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    annotations:
        cache:          file
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        lifetime:       3600
        name:           symfony

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        vespolina_layout_template: VespolinaStoreBundle::layout.html.twig
#    form:
#      resources:
#        - 'MopaBootstrapBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ VespolinaAdminBundle]
    java:           %java_path%
    filters:
        cssrewrite: ~
        less:
            node: %nodepath%
            node_paths: [%nodemodulearray%]
        yui_css:
             jar: %yui_compressor_jar%
        yui_js:
             jar: %yui_compressor_jar%
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
                mappings:
                    #SonataMediaBundle: ~
                    VespolinaTaxationBundle: ~
                    VespolinaStoreBundle: ~


doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_document_manager: default
    default_database: %mongodb_database_name%_%kernel.environment%
    document_managers:
        default:
            #auto_mapping: true
            mappings:
                FOSUserBundle: ~
                VespolinaPricingBundle: ~
                VespolinaStoreBundle: ~
                VespolinaTaxationBundle: ~
                VespolinaTaxonomyBundle: ~
                UserBundle: ~
                VespolinaProduct:
                    mapping:              true
                    type:                 xml
                    dir:                  "%kernel.root_dir%/../vendor/vespolina/product/lib/Vespolina/Product/Mapping"
                    alias:                ~
                    prefix:               Vespolina\Entity\Product
                    is_bundle:            false
                VespolinaOrder:
                    mapping:              true
                    type:                 xml
                    dir:                  "%kernel.root_dir%/../vendor/vespolina/order/lib/Vespolina/Order/Mapping"
                    alias:                ~
                    prefix:               Vespolina\Entity\Order
                    is_bundle:            false
                VespolinaPartner:
                    mapping:              true
                    type:                 xml
                    dir:                  "%kernel.root_dir%/../vendor/vespolina/partner/lib/Vespolina/Partner/Mapping"
                    alias:                ~
                    prefix:               Vespolina\Entity\Partner
                    is_bundle:            false
                VespolinaPricing:
                    mapping:              true
                    type:                 xml
                    dir:                  "%kernel.root_dir%/../vendor/vespolina/pricing/lib/Vespolina/Pricing/Mapping"
                    alias:                ~
                    prefix:               Vespolina\Entity\Pricing
                    is_bundle:            false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#fos_rest:
#    routing_loader:
#        default_format: json

mopa_bootstrap:

#sonata_media:
#    db_driver: doctrine_orm # or doctrine_mongodb
#    contexts:
#        default:  # the default context is mandatory
#            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#                - sonata.media.provider.file
#
#            formats:
#                small: { width: 100 , quality: 70}
#                big:   { width: 500 , quality: 70}
#
#    cdn:
#        sonata.media.cdn.server:
#            path: /uploads/media # http://media.sonata-project.org/
#
#    filesystem:
#        sonata.media.adapter.filesystem.local:
#            directory:  %kernel.root_dir%/../web/uploads/media
#            create:     true


sensio_framework_extra:
    view:
        annotations: false
