
vespolina_store:
    resource: "@VespolinaStoreBundle/Resources/config/routing/store.xml"
    prefix:   /

vespolina_product:
    resource: "@VespolinaProductBundle/Resources/config/routing/product.xml"
    prefix:   /product/

vespolina_fulfillment:
    resource: "@VespolinaFulfillmentBundle/Resources/config/routing.xml"
    prefix:   /

default:
    resource: @DefaultBundle/Resources/config/routing.yml

fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml

vespolina_admin:
    resource: @VespolinaAdminBundle/Resources/config/routing/admin.xml
    prefix:   /admin/

vespolina_product_admin:
    resource: @VespolinaProductBundle/Resources/config/routing/admin.xml
    prefix:   /admin/product
