vespolina_store:
    db_driver: mongodb
    default_store: default_store
    multi_store: false
vespolina_cart:
    db_driver: mongodb
vespolina_pricing:
    db_driver: mongodb
vespolina_product:
    db_driver: mongodb
    product_manager:
#        primary_identifier: sku
        identifiers:
            sku: Vespolina\ProductBundle\Document\SKUIdentifier
    product:
        form:
            type:               Application\Vespolina\ProductBundle\Form\Type\ProductFormExtendedType #vespolina.product.form.type
#            handler_service:    vespolina.product.form.handler
#            name:               vespolina_product_form
vespolina_taxation:
    db_driver: orm
#    tax_mode: default_tax_rate   #flat_tax_rate, default_tax_rate, mixed_tax_rates
vespolina_monetary:
    currency:
        base_currency:  EUR